### ISSUE TITLE
Demo site is broken for Safari

### ISSUE THREAD

**Issue by divan** [lifegadget/ui-list#1]
Hey,

demo/docs site doesn't open in Safari (8.0.5). Just a blank page, and JS error in console:

   [Error] SyntaxError: Attempted to redefine property 'filter'.(dummy.js, line 3262)

In Chrome it works fine.

**Comment by ksnyde** [comment]
Thanks for the heads up. I have been doing all my testing to date on Chrome but obviously want to support Safari.

**Comment by ksnyde** [comment]
I have been looking forward to having the Component inputs mapped onto a `props` namespace which I think comes in on 1.13.x of Ember I believe. I think this will address this issue as the API surface of the component includes a `filter` property which is set to a initialized/default state and I think it's seeing filter as a reserved property for a input control. If that's the issue then it's not hard to fix. I'm pretty buried at the moment but hopefully will have cycles in a few days time.

**Comment by ksnyde** [comment]
Ok, fixing that error was very easy. I've committed it now to the #develop branch and will push to master in a second (as well as update divshot). The only reason I'm not celebrating is that on the next page of the demo (e.g., click on the `ui-item` link for instance) you'll get an error that I believe is ES6 related:

https://github.com/google/traceur-compiler/issues/1650

**Comment by ksnyde** [comment]
please let me know if you're still experiencing this
