### ISSUE TITLE
Installation error (version 0.0.8)

### ISSUE THREAD

**Issue by xxdeveloper** [lifegadget/ui-list#3]
As result "ember install ui-list" (ember-cli 0.2.7):
The package 'ui-list' is not a properly formatted package, we have used a fallback lookup to resolve it at '..\node_modules\ui-list'. This is generally caused by an addon not having a 'main' entry point (or 'index.js').
The 'ui-list' addon could not be found at '..\node_modules\ui-list'.

**Comment by ksnyde** [comment]
Yeah this is a known **npm** issue. I have fixed in many of projects but I guess I must not have on this one. I'll try and get to this tonight.

**Comment by ksnyde** [comment]
I've release version `0.0.9` on npm. let me know if that corrects things for you.

**Comment by xxdeveloper** [comment]
It works great (version 0.0.9). Thank you, very quick fix.
