### ISSUE TITLE
Lightning Talk and Introduction Video

### ISSUE THREAD

**Issue by taras** [lifegadget/ui-list#4]
I came across this addon on Ember Addons and I really like how you documented the addon.
I was wondering you'd be interested in giving a lightning talk about your addon on http://www.meetup.com/Ember-Global-Meetup. The talk would be a screen sharing session from your computer and you can give an introduction to the addon and how it should be used. I'll edit the video afterwards and you can put it into the README of the addon. 

What do you think?

**Comment by ksnyde** [comment]
Hi @taras I'd be happy to do that. What sort of timeframe were you thinking?

**Comment by taras** [comment]
We have scheduled talks for Sept 12th and Sept 26th and unscheduled for next month. A lightning talk is about 15-20 minutes.

**Comment by ksnyde** [comment]
I think the 26th might work. Do you have an example of a lightning talk I could watch?

**Comment by taras** [comment]
I don't have an example yet because this is a new thing that we're doing but we'll have one after our talk on September 12th. 

In terms of content, I'd suggest something like:
 - Why did you create this addon? i.e. what issue does it aim to solve?
 - How to get started?
 - What should people be aware of?
 - What would you like to improve? (are you looking for help?)

**Comment by ksnyde** [comment]
Ok, seems like a good outline. Why don't we sign me up for the 26th. 

> p.s. when you do have some material from the 12th available, where will it be hosted?

**Comment by ksnyde** [comment]
Oh ... what time of day is the 26th event? Just realised that I'm obligated to be at a birthday party that day. Well let me know ... maybe I'll have to do the next one. Sorry to drag this out but we'll get it sorted. :)

**Comment by taras** [comment]
It's 12:00 EST. We can do it on October 10th if that works better for you

**Comment by ksnyde** [comment]
I'm NYC running a race on 10 Oct. I think I'll squeeze my way out of the birthday event. You count me in for Sept 26th.

**Comment by taras** [comment]
Awesome!

**Comment by taras** [comment]
I see that you have a lot of components. Do you want me call the talk *Introduction to `ui-list`* or something else?

**Comment by ksnyde** [comment]
**ui-list** is fine as a centrepiece and I'll probably mention the "family" of component during the talk. Looking forward to it. :)

**Comment by taras** [comment]
Cool, will announce it shortly.
